# Site settings
title: marsdenstudios
email: marsdenstudios@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A small design company based in Stroud.
baseurl:  # the subpath of your site, e.g. /home/
url:  # the base hostname & protocol for your site
facebook_username: marsdenstudios
github_username:  marsdenstudios

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/home/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  workshops:
    output: true
    permalink: /workshops/:path/
