# Site settings
title: *folio
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /home/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/home/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  workshops:
    output: true
    permalink: /workshops/:path/
